name: cpp-linter
on:
  pull_request:
    branches: [main]
    paths: ["**.c", "**.cpp", "**.h", "**.hpp", "**.cc"]
  push:
    branches: [main]
    paths: ["**.c", "**.cpp", "**.h", "**.hpp", "**.cc"]

permissions:
  pull-requests: read
  contents: write
  statuses: write

jobs:
  cpp-linter:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v5.0.0
        with:
          # get all the branches and tags
          fetch-depth: 0
          persist-credentials: false

      - name: cpp linter
        uses: cpp-linter/cpp-linter-action@v2.16.5
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: "file" # Use .clang-format config file.
          tidy-checks: "-*" # disable clang-tidy checks.
          file-annotations: "true" # Enable file annotations.
          # only 'update' a single comment in a pull request thread.
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          step-summary: "true" # Add a job step summary with results.
          format-review: "true" # Enable format review.

      - name: validation
        if: steps.linter.outputs.clang-format-checks-failed > 0
        run: echo "Linting issues failed!"

      - name: Commit and push linting fixes
        # Run only on:
        # - Pull requests
        # - Not on the default branch
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "super-linter: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
